name: Tests

on: [pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup environment
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Setup dependencies
              run: yarn

            - name: Setup lerna
              run: yarn setup

            - name: Build packages
              run: yarn workspaces run build

            - name: run tests
              run: yarn test
